### ISSUE TITLE
Admin access for topics repo

### ISSUE THREAD

**Issue by jkarlin** [patcg-individual-drafts/admin#2]
@AramZS can you provide admin access to the Topics repo to myself and @xyaoinum ? We'd like to configure the repo to have previews of spec changes in PR requests.

**Comment by AramZS** [comment]
Done

**Comment by jkarlin** [comment]
Thanks!

**Comment by balajitours** [comment]
Bangalore to Tirupati Darshan Package 
Balaji Darshan Package 
Tirupati Balaji tours package 
Tirupati Tirumala Balaji Darshan Package 

![Image](https://github.com/user-attachments/assets/7e76a504-94fb-48f7-a37b-38651388984a)[
